server:
  port: 7001

spring:
  datasource:
    url: jdbc:h2:mem:dbsd
    username: sd
    password: sd
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: "true"
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: "true"
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: "true"
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
