server:
  port: 7002

file-path: target/output/database-to-file

spring:
  batch:
    job:
      enabled: false
  datasource:
    url: jdbc:h2:mem:dbsb
    username: sb
    password: sb
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: "true"
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: "true"
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: "true"
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
